title: St. Anthony Youth

url: https://stanthonynovato.org
baseurl: "" # Set to empty string for local development, GitHub Actions will override this
email: ale@stanthonynovato.org
phone: +1 (800) 242-8478
admin_email: damien@alphagame.dev
permalink: /news/:year/:month/:title
description: >- # this means to ignore newlines until "baseurl:"
  St. Anthony de Padua Catholic Parish Confirmation Program, guiding youth 
  to a deeper relationship with Christ and the Church.

# TODO: replace with actual social media.
# facebook_username: StAnthonyDepaduaParish
instagram_username: stanthonyyouth.novato

publisher: "St. Anthony de Padua Catholic Parish"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-dotenv
  - jekyll-news-sitemap
  - jekyll-paginate
  - jekyll-sass-converter
  - jekyll-minifier
  - jekyll-resize

# Jekyll Minifier configuration
jekyll-minifier:
  uglifier_args:
    harmony: true
    compress:
      drop_console: false
    mangle: true

# Sass/SCSS configuration
sass:
  sass_dir: _sass
  style: expanded # This will expand the CSS output

# Directories to exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

# Pagination settings
paginate: 5
paginate_path: "/news/page/:num/"

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      sitemap: 
exclude:
  - LICENSE # only for the repo lol
  - README.md # only for the repo lol
  - seo.py