title: St. Anthony Youth

email: ale@stanthonynovato.org
admin_email: damien@alphagame.dev
permalink: /news/:year/:month/:title
description: >- # this means to ignore newlines until "baseurl:"
  St. Anthony de Padua Catholic Parish Confirmation Program, guiding youth 
  to a deeper relationship with Christ and the Church.

# TODO: replace with actual social media.
# facebook_username: StAnthonyDepaduaParish
# instagram_username: stanthonypadua

publisher: St. Anthony de Padua Catholic Parish
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-dotenv
  - jekyll-news-sitemap
  - jekyll-paginate
  - jekyll-sass-converter

# Sass/SCSS configuration
sass:
  sass_dir: _sass
  style: compressed # This will minify the CSS output

# Directories to exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

# Pagination settings
paginate: 5
paginate_path: "/news/page/:num/"

exclude:
  - LICENSE # only for the repo lol
  - README.md # only for the repo lol
  - seo.py