title: St. Anthony Youth

email: ale@stanthonypadua.org
admin_email: damien@alphagame.dev
permalink: /news/:year/:month/:title
description: >- # this means to ignore newlines until "baseurl:"
  St. Anthony de Padua Catholic Parish Confirmation Program, guiding youth 
  to a deeper relationship with Christ and the Church.

copyright: "&copy; 2025 St. Anthony Youth Leadership Team"

# TODO: replace with actual social media.
# facebook_username: StAnthonyDepaduaParish
# instagram_username: stanthonypadua

publisher: St. Anthony de Padua Catholic Parish
plugins:
  - jekyll-feed
  - jekyll-dotenv
  - jekyll-news-sitemap
  - jekyll-paginate

# Pagination settings
paginate: 5
paginate_path: "/news/page/:num/"
