name: Lighthouse CI (Jekyll Serve)

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v4

      - name: 💎 Set up Ruby (for Jekyll)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: 🧰 Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Install dependencies
        run: |
          gem install bundler
          bundle install
          npm install
          npm install -g wait-on

      - name: 🚀 Start Jekyll Server in background
        run: |
          JEKYLL_ENV=production bundle exec jekyll serve --port 4000 --host 127.0.0.1 &
          echo $! > jekyll.pid

      - name: 🕰 Wait for server to be ready
        run: wait-on http://127.0.0.1:4000

      - name: 🔦 Run Lighthouse Audit
        run: |
          npx lhci collect --url=http://127.0.0.1:4000 \
            --settings.emulatedFormFactor=desktop

      - name: 🧼 Kill Jekyll Server
        run: |
          kill $(cat jekyll.pid)
          
      - name: 📊 Generate Lighthouse Report
        id: lighthouse-report
        run: |
          python3 ci/gen-lh-comment.py > lighthouse-report.md
          echo "report-generated=true" >> $GITHUB_OUTPUT

      - name: 💬 Comment PR with Lighthouse Results
        if: steps.lighthouse-report.outputs.report-generated == 'true'
        uses: thollander/actions-comment-pull-request@v3
        with:
          file-path: lighthouse-report.md
          comment-tag: lighthouse-ci
          mode: recreate
